"""Codex hard-interrupt notice conversion for Chat-provider cache stability."""

from __future__ import annotations

import copy
import json
from typing import Any

from codex_rosetta.auto_detect import ProviderType

_TURN_ABORTED_OPEN = "<turn_aborted>"
_TURN_ABORTED_CLOSE = "</turn_aborted>"
_DEVELOPER_GUIDANCE = (
    "The previous turn was interrupted on purpose. Any running unified exec "
    "processes may still be running in the background. If any tools/commands "
    "were aborted, they may have partially executed."
)
_USER_GUIDANCE = (
    "The user interrupted the previous turn on purpose. Any running unified exec "
    "processes may still be running in the background. If any tools/commands "
    "were aborted, they may have partially executed."
)

TURN_ABORTED_DEVELOPER_TEXT = (
    f"{_TURN_ABORTED_OPEN}\n{_DEVELOPER_GUIDANCE}\n{_TURN_ABORTED_CLOSE}"
)
TURN_ABORTED_USER_TEXT = (
    f"{_TURN_ABORTED_OPEN}\n{_USER_GUIDANCE}\n{_TURN_ABORTED_CLOSE}"
)
CODEX_RUNTIME_NOTICE_SUFFIX = (
    "This notice was generated by Codex and was not written by the user.\n"
    "</codex_runtime_notice>"
)

_CANONICAL_MARKERS = {
    "developer": TURN_ABORTED_DEVELOPER_TEXT,
    "system": TURN_ABORTED_DEVELOPER_TEXT,
    "user": TURN_ABORTED_USER_TEXT,
}
_CODEX_METADATA_MAX_ID_CHARS = 512


def _has_valid_codex_turn_metadata(body: dict[str, Any]) -> bool:
    metadata = body.get("client_metadata")
    if not isinstance(metadata, dict):
        return False
    raw = metadata.get("x-codex-turn-metadata")
    if not isinstance(raw, str) or len(raw) > 16 * 1024:
        return False
    try:
        decoded = json.loads(raw)
    except TypeError, ValueError:
        return False
    if not isinstance(decoded, dict) or decoded.get("request_kind") != "turn":
        return False
    for field in ("session_id", "thread_id", "turn_id"):
        value = decoded.get(field)
        if (
            not isinstance(value, str)
            or not value.strip()
            or len(value) > _CODEX_METADATA_MAX_ID_CHARS
        ):
            return False
    return True


def _message_text(item: dict[str, Any]) -> str | None:
    content = item.get("content")
    if isinstance(content, str):
        return content
    if (
        isinstance(content, list)
        and len(content) == 1
        and isinstance(content[0], dict)
        and content[0].get("type") == "input_text"
        and isinstance(content[0].get("text"), str)
    ):
        return content[0]["text"]
    return None


def _wrapped_notice(marker: str) -> str:
    return f"<codex_runtime_notice>\n{marker}\n{CODEX_RUNTIME_NOTICE_SUFFIX}"


def _rewrite_item(item: Any) -> tuple[Any, bool]:
    if not isinstance(item, dict) or item.get("type") != "message":
        return item, False
    role = item.get("role")
    marker = _CANONICAL_MARKERS.get(role) if isinstance(role, str) else None
    if marker is None or _message_text(item) != marker:
        return item, False

    rewritten = copy.deepcopy(item)
    rewritten["role"] = "user"
    content = rewritten.get("content")
    notice = _wrapped_notice(marker)
    if isinstance(content, str):
        rewritten["content"] = notice
    else:
        rewritten["content"] = [{"type": "input_text", "text": notice}]
    return rewritten, True


def rewrite_codex_interrupt_notices(
    body: dict[str, Any],
    *,
    enabled: bool,
    source_provider: ProviderType,
    target_provider: ProviderType,
) -> tuple[dict[str, Any], int]:
    """Rewrite exact Codex abort markers as attributed user-role notices.

    This is intentionally a request-local conversion. It never retains model
    output, waits for an abandoned stream, or replays content into a later turn.

    Args:
        body: Parsed inbound request body.
        enabled: Effective Provider compatibility setting.
        source_provider: Inbound protocol selected by the route.
        target_provider: Upstream protocol selected by the route.

    Returns:
        The original body and zero when no item matches, otherwise a copy with
        every exact canonical marker rewritten and the number of rewritten items.
    """
    if (
        not enabled
        or source_provider not in {"openai_responses", "open_responses"}
        or target_provider != "openai_chat"
        or not _has_valid_codex_turn_metadata(body)
    ):
        return body, 0
    items = body.get("input")
    if not isinstance(items, list):
        return body, 0

    rewritten_items: list[Any] = []
    count = 0
    for item in items:
        rewritten, changed = _rewrite_item(item)
        rewritten_items.append(rewritten)
        count += int(changed)
    if count == 0:
        return body, 0

    rewritten_body = body.copy()
    rewritten_body["input"] = rewritten_items
    return rewritten_body, count
