<script lang="ts">
  import{onMount}from'svelte';import Modal from'../components/Modal.svelte';import ModelTestPanel from'../components/ModelTestPanel.svelte';import{api}from'../lib/api';import{t}from'../../shared/i18n.svelte';
  type ReasoningLevel=string|{effort?:string};type ModelInfo=Record<string,unknown>&{slug:string;display_name:string;description:string;identity?:string;priority:number;context_window:number;input_modalities:string[];supported_reasoning_levels:ReasoningLevel[]};type RuntimeCapabilities={temperature?:number|null;top_p?:number|null};type ModelEntry={upstream_model?:string;model_info?:ModelInfo;runtime_capabilities?:RuntimeCapabilities;preset_slug?:string|null;has_overrides?:boolean;validation_error?:string};type Group={provider?:string;type?:string;tool_profile?:string;models?:Record<string,ModelEntry>;validation_error?:string};type Preset=ModelInfo;type Dict=Record<string,unknown>;type ProfileApiType='chat'|'responses'|'anthropic'|'google';type ToolProfile={id:string;name:string;api_types:ProfileApiType[]};type ToolProfileOption={id:string;api_types:ProfileApiType[]};type ProviderCatalogEntry={label_key:string;runtime_capability_fields?:Array<keyof RuntimeCapabilities>;runtime_capabilities_by_model?:Record<string,RuntimeCapabilities>};type Config={providers?:Record<string,{enabled?:boolean;api_type?:string;provider?:string}>;provider_catalog?:{providers:Record<string,ProviderCatalogEntry>};model_groups?:Record<string,Group>;models?:Record<string,unknown>;tool_profiles?:Record<string,{api_types:ProfileApiType[]}>;tool_profile_presets?:ToolProfile[];tool_profile_passthrough_option?:ToolProfileOption;model_presets?:Preset[];codex?:Dict;server?:Dict};type Row={id:number;name:string;upstream:string;info:ModelInfo|null;runtime:RuntimeCapabilities;modified:boolean};
  let config=$state<Config>({});let name=$state('');let originalName=$state('');let provider=$state('');let toolProfile=$state('');let rows=$state<Row[]>([]);let rowSequence=0;let discovered=$state<string[]>([]);let discoveryFilter=$state('');let selectedDiscovered=$state(new Set<string>());let prefix=$state('');let loading=$state(true);let busy=$state(false);let error=$state('');let notice=$state('');let groupOpen=$state(false);let fetchOpen=$state(false);let infoRowId=$state<number|null>(null);let infoDraft=$state<ModelInfo|null>(null);let limitRowId=$state<number|null>(null);let runtimeDraft=$state<RuntimeCapabilities>({});let providerFilter=$state('');let search=$state('');let collapsed=$state(new Set<string>());let reviewModel=$state('');let consolidationModel=$state('');let extractModel=$state('');
  let filteredDiscovered=$derived(discovered.filter((item)=>item.toLowerCase().includes(discoveryFilter.trim().toLowerCase())));let configuredModels=$derived(Object.keys(config.models??{}).sort());let providerApiType=$derived(config.providers?.[provider]?.api_type as ProfileApiType|undefined);let passthroughOption=$derived(config.tool_profile_passthrough_option?.api_types.includes(providerApiType as ProfileApiType)?config.tool_profile_passthrough_option:undefined);let compatibleToolProfiles=$derived.by(():ToolProfile[]=>[...(config.tool_profile_presets??[]),...Object.entries(config.tool_profiles??{}).map(([id,profile])=>({id,name:id,api_types:profile.api_types}))].filter((profile)=>providerApiType!==undefined&&profile.api_types.includes(providerApiType)));
  const message=(value:unknown)=>value instanceof Error?value.message:String(value);const copyInfo=(info:ModelInfo):ModelInfo=>JSON.parse(JSON.stringify(info))as ModelInfo;const copyRuntime=(value:RuntimeCapabilities):RuntimeCapabilities=>JSON.parse(JSON.stringify(value))as RuntimeCapabilities;const sameJson=(left:unknown,right:unknown):boolean=>JSON.stringify(left)===JSON.stringify(right);const blankInfo=(row:Row):ModelInfo=>({slug:row.upstream||row.name,display_name:row.name,description:row.name,identity:row.name,priority:1,context_window:128000,input_modalities:['text'],supported_reasoning_levels:['medium']});const reasoningValues=(info:ModelInfo):string[]=>info.supported_reasoning_levels.map((item)=>typeof item==='string'?item:item.effort??'').filter(Boolean);const selectedProviderCatalog=():ProviderCatalogEntry|undefined=>{const id=config.providers?.[provider]?.provider;return id?config.provider_catalog?.providers[id]:undefined;};const runtimeFields=():Array<keyof RuntimeCapabilities>=>selectedProviderCatalog()?.runtime_capability_fields??[];const matchedProviderRuntimePreset=(row:Row):RuntimeCapabilities|undefined=>{const presets=selectedProviderCatalog()?.runtime_capabilities_by_model??{};if(Object.prototype.hasOwnProperty.call(presets,row.upstream))return presets[row.upstream];if(row.upstream!==row.name&&Object.prototype.hasOwnProperty.call(presets,row.name))return presets[row.name];return undefined;};const providerRuntimePreset=(row:Row):RuntimeCapabilities=>copyRuntime(matchedProviderRuntimePreset(row)??{});const hasProviderExtraConfig=(row:Row):boolean=>matchedProviderRuntimePreset(row)!==undefined;const providerDisplayName=():string=>provider;
  function presetFor(row:Row):Preset|undefined{const presets=config.model_presets??[];return presets.find((item)=>item.slug===row.upstream)||presets.find((item)=>item.slug===row.name);}function addRow(modelName='',entry:ModelEntry={}):void{rows=[...rows,{id:++rowSequence,name:modelName,upstream:entry.upstream_model??'',info:entry.model_info?copyInfo(entry.model_info):null,runtime:{...(entry.runtime_capabilities??{})},modified:entry.has_overrides===true}];}function closeInfo():void{infoRowId=null;infoDraft=null;}function closeLimits():void{limitRowId=null;runtimeDraft={};}function closeEditors():void{closeInfo();closeLimits();}function removeRow(id:number):void{rows=rows.filter((row)=>row.id!==id);if(infoRowId===id)closeInfo();if(limitRowId===id)closeLimits();}function infoRow():Row|undefined{return rows.find((row)=>row.id===infoRowId);}function limitRow():Row|undefined{return rows.find((row)=>row.id===limitRowId);}function editInfo(row:Row):void{closeLimits();infoDraft=copyInfo(row.info??presetFor(row)??blankInfo(row));infoRowId=row.id;}function editLimits(row:Row):void{closeInfo();runtimeDraft=copyRuntime(Object.keys(row.runtime).length?row.runtime:providerRuntimePreset(row));limitRowId=row.id;}function toolProfileAvailable(nextProvider:string,id:string):boolean{const apiType=config.providers?.[nextProvider]?.api_type as ProfileApiType|undefined;const special=config.tool_profile_passthrough_option;if(special?.id===id)return apiType!==undefined&&special.api_types.includes(apiType);return[...(config.tool_profile_presets??[]),...Object.entries(config.tool_profiles??{}).map(([profileId,profile])=>({id:profileId,api_types:profile.api_types}))].some((profile)=>profile.id===id&&apiType!==undefined&&profile.api_types.includes(apiType));}function changeProvider(next:string):void{provider=next;closeEditors();if(toolProfile&&!toolProfileAvailable(next,toolProfile))toolProfile='';}function toggleList(field:'input_modalities'|'supported_reasoning_levels',value:string,checked:boolean):void{if(!infoDraft)return;const current=new Set(field==='input_modalities'?infoDraft.input_modalities:reasoningValues(infoDraft));checked?current.add(value):current.delete(value);infoDraft[field]=[...current];}function toggleRuntime(field:keyof RuntimeCapabilities,checked:boolean):void{if(checked)runtimeDraft={...runtimeDraft,[field]:1};else{const next={...runtimeDraft};delete next[field];runtimeDraft=next;}}function setRuntime(field:keyof RuntimeCapabilities,value:number|null):void{runtimeDraft={...runtimeDraft,[field]:value};}
  function infoStatus(row:Row):{text:string;detected:boolean;modified:boolean}{const preset=presetFor(row);if(!preset)return{text:t('modelInfo.notDetected'),detected:false,modified:row.modified};const modified=row.modified;return{text:t(modified?'modelInfo.detectedModified':'modelInfo.detected',{display_name:preset.display_name}),detected:true,modified};}
  function markModified(row:Row):void{const preset=presetFor(row);row.modified=!preset||!!row.info&&!sameJson(row.info,preset)||!sameJson(row.runtime,providerRuntimePreset(row));}function clearInfo():void{const row=infoRow();if(row){row.info=null;markModified(row);rows=[...rows];}closeInfo();}function applyInfo():void{const row=infoRow();if(!row||!infoDraft)return;const stringsReady=[infoDraft.slug,infoDraft.display_name,infoDraft.description,String(infoDraft.identity??'')].every((value)=>value.trim());if(!stringsReady||!Number.isInteger(infoDraft.priority)||infoDraft.priority<=0||!Number.isInteger(infoDraft.context_window)||infoDraft.context_window<=0||!infoDraft.input_modalities.length||!reasoningValues(infoDraft).length){error=t('modelInfo.completeRequired');return;}row.info=copyInfo(infoDraft);markModified(row);rows=[...rows];closeInfo();}function clearLimits():void{const row=limitRow();if(row){row.runtime=providerRuntimePreset(row);markModified(row);rows=[...rows];}closeLimits();}function applyLimits():void{const row=limitRow();if(!row)return;for(const field of runtimeFields()){const value=runtimeDraft[field];const maximum=field==='temperature'?2:1;if(value!==undefined&&value!==null&&(!Number.isFinite(value)||value<0||value>maximum)){error=t('modelInfo.limitRange',{field,max:maximum});return;}}row.runtime=copyRuntime(runtimeDraft);markModified(row);rows=[...rows];closeLimits();}
  function hydrate(next:Config):void{config=next;if(!provider)provider=Object.keys(next.providers??{})[0]??'';const codex=next.codex??{};const memories=(codex.memories&&typeof codex.memories==='object'?codex.memories:{})as Dict;reviewModel=String(codex.auto_review_model_override??'');consolidationModel=String(memories.consolidation_model??'');extractModel=String(memories.extract_model??'');}
  async function load(signal?:AbortSignal):Promise<void>{try{hydrate(await api.get<Config>('/admin/api/config',signal));error='';}catch(cause){if(!(cause instanceof DOMException&&cause.name==='AbortError'))error=message(cause);}finally{loading=false;}}
  function reset():void{name='';originalName='';provider=Object.keys(config.providers??{})[0]??'';toolProfile='';rows=[];addRow();discovered=[];selectedDiscovered=new Set();discoveryFilter='';prefix='';closeEditors();error='';notice='';}
  function openNew():void{reset();groupOpen=true;}function edit(groupName:string,group:Group):void{name=groupName;originalName=groupName;provider=group.provider??'';toolProfile=group.tool_profile??'';rows=[];for(const[modelName,entry]of Object.entries(group.models??{}))addRow(modelName,entry);if(!rows.length)addRow();discovered=[];selectedDiscovered=new Set();closeEditors();error='';groupOpen=true;}
  function modelPayload():Record<string,ModelEntry>{const output:Record<string,ModelEntry>={};for(const row of rows){const exposed=row.name.trim();if(!exposed)continue;if(output[exposed])throw new Error(t('error.duplicateModel',{model:exposed}));const entry:ModelEntry={};if(row.upstream.trim())entry.upstream_model=row.upstream.trim();if(row.info)entry.model_info=copyInfo(row.info);if(!sameJson(row.runtime,providerRuntimePreset(row)))entry.runtime_capabilities=copyRuntime(row.runtime);output[exposed]=entry;}if(!Object.keys(output).length)throw new Error(t('error.addAtLeastOneModel'));return output;}
  async function save():Promise<void>{if(!name.trim()||!provider){error=t('error.modelGroupNameProviderRequired');return;}busy=true;error='';try{const body:Record<string,unknown>={provider,type:'llm',models:modelPayload()};if(toolProfile)body.tool_profile=toolProfile;if(originalName&&originalName!==name.trim())body.rename_from=originalName;await api.put(`/admin/api/config/model-groups/${encodeURIComponent(name.trim())}`,body);notice=t('toast.modelGroupSaved',{name:name.trim()});groupOpen=false;await load();}catch(cause){error=message(cause);}finally{busy=false;}}
  async function remove(groupName:string):Promise<void>{if(!confirm(t('confirm.deleteModelGroup',{name:groupName})))return;busy=true;error='';try{await api.del(`/admin/api/config/model-groups/${encodeURIComponent(groupName)}`);await load();notice=t('toast.modelGroupDeleted',{name:groupName});}catch(cause){error=message(cause);}finally{busy=false;}}
  async function discover():Promise<void>{if(!provider)return;busy=true;error='';discovered=[];selectedDiscovered=new Set();try{const result=await api.get<{models?:string[];error?:string}>(`/admin/api/config/providers/${encodeURIComponent(provider)}/models`);if(result.error)throw new Error(result.error);discovered=result.models??[];}catch(cause){error=message(cause);}finally{busy=false;}}
  function selectModel(model:string,checked:boolean):void{const next=new Set(selectedDiscovered);checked?next.add(model):next.delete(model);selectedDiscovered=next;}function addSelected():void{const existing=new Set(rows.map((row)=>row.name));for(const upstream of discovered)if(selectedDiscovered.has(upstream)){const exposed=`${prefix}${upstream}`;if(!existing.has(exposed)){addRow(exposed,{upstream_model:prefix?upstream:undefined});existing.add(exposed);}}selectedDiscovered=new Set();fetchOpen=false;groupOpen=true;}
  function openFetch():void{reset();fetchOpen=true;}function toggleGroup(groupName:string):void{const next=new Set(collapsed);next.has(groupName)?next.delete(groupName):next.add(groupName);collapsed=next;}function visibleGroup(groupName:string,group:Group):boolean{if(providerFilter&&group.provider!==providerFilter)return false;const query=search.trim().toLowerCase();return!query||[groupName,group.provider,...Object.keys(group.models??{})].some((item)=>String(item??'').toLowerCase().includes(query));}
  async function saveTaskModels():Promise<void>{busy=true;error='';try{await api.put('/admin/api/config/codex',{auto_review_model_override:reviewModel||null,memories:{consolidation_model:consolidationModel||null,extract_model:extractModel||null}});notice=t('toast.codexTaskModelsSaved');await load();}catch(cause){error=message(cause);}finally{busy=false;}}
  onMount(()=>{reset();const controller=new AbortController();void load(controller.signal);return()=>controller.abort();});
</script>
<div class="section"><div class="section-header"><h2>{t('section.codexTaskModels')}</h2></div><div class="codex-task-model-grid"><div class="codex-task-model-field"><label for="autoReviewModel">{t('label.autoApprovalModel')}</label><select id="autoReviewModel" bind:value={reviewModel} onchange={()=>void saveTaskModels()}><option value="">{t('format.defaultModel',{model:'codex-auto-review'})}</option>{#each configuredModels as model}<option value={model}>{model}</option>{/each}</select></div><div class="codex-task-model-field"><label for="memoryConsolidationModel">{t('label.memoryConsolidationModel')}</label><select id="memoryConsolidationModel" bind:value={consolidationModel} onchange={()=>void saveTaskModels()}><option value="">{t('format.defaultModel',{model:'gpt-5.4'})}</option>{#each configuredModels as model}<option value={model}>{model}</option>{/each}</select></div><div class="codex-task-model-field"><label for="memoryExtractModel">{t('label.memoryExtractModel')}</label><select id="memoryExtractModel" bind:value={extractModel} onchange={()=>void saveTaskModels()}><option value="">{t('format.defaultModel',{model:'gpt-5.4-mini'})}</option>{#each configuredModels as model}<option value={model}>{model}</option>{/each}</select></div></div></div>
<div class="section"><div class="section-header"><h2>{t('section.models')}</h2><div style="display:flex;gap:6px"><button class="btn btn-sm" onclick={openFetch}>{t('btn.fetchModels')}</button><button class="btn btn-sm" onclick={openNew}>{t('btn.addModelGroup')}</button></div></div>{#if error}<div class="toast error show" role="alert">{error}</div>{/if}{#if notice}<div class="toast show" role="status">{notice}</div>{/if}<div class="model-toolbar"><select aria-label={t('aria.providerFilter')} bind:value={providerFilter}><option value="">{t('filter.allProviders')}</option>{#each Object.keys(config.providers??{}) as item}<option value={item}>{item}</option>{/each}</select><input aria-label={t('aria.searchModels')} bind:value={search} placeholder={t('placeholder.searchModels')} /><span class="model-count">{t('format.modelCount',{count:Object.keys(config.models??{}).length})}</span></div>
{#if loading}<p style="color:var(--text-dim)">{t('loading.modelGroups')}</p>{:else}<div class="model-group-list">{#each Object.entries(config.model_groups??{}) as [groupName,group]}{#if visibleGroup(groupName,group)}<div class="model-group-card" class:collapsed={collapsed.has(groupName)} class:config-error={!!group.validation_error}><div class="model-group-head"><div class="model-group-title"><button class="key-btn model-group-toggle" aria-label={t('aria.toggleGroup')} onclick={()=>toggleGroup(groupName)}>{collapsed.has(groupName)?'▸':'▾'}</button><code>{groupName}</code>{#if group.validation_error}<span class="badge badge-error" title={group.validation_error}>{t('model.configError')}</span>{/if}<span class="model-group-meta">{[(group.type??'llm')==='llm'?t('label.llm'):group.type,group.provider??'',...(group.tool_profile?[group.tool_profile]:[]),`${Object.keys(group.models??{}).length}`].join(' · ')}</span></div><div class="model-group-actions"><button class="btn btn-sm" onclick={()=>edit(groupName,group)}>{t('btn.edit')}</button><button class="btn btn-sm btn-danger" disabled={busy} onclick={()=>void remove(groupName)}>{t('btn.delete')}</button></div></div><div class="model-group-body"><div class="table-scroll"><table><tbody>{#each Object.entries(group.models??{}) as [modelName,entry]}<tr style:opacity={config.providers?.[group.provider??'']?.enabled===false?0.4:1}><td><code>{modelName}</code>{#if entry.upstream_model}<span style="font-size:11px;color:var(--text-dim)"> → {entry.upstream_model}</span>{/if}{#each entry.model_info?.input_modalities??[] as modality}<span class="badge badge-cap">{t(`modelInfo.modality.${modality}`)}</span>{/each}</td><td>{group.provider??''}</td><td style="text-align:right"><ModelTestPanel model={modelName}/></td></tr>{/each}</tbody></table></div></div></div>{/if}{:else}<div style="color:var(--text-dim);font-size:13px">{t('empty.modelGroups')}</div>{/each}</div>{/if}</div>

<Modal open={groupOpen} labelledby="model-group-title" wide onclose={()=>{groupOpen=false;closeEditors();}}>
  {#snippet header()}<h3 id="model-group-title">{originalName?t('modal.editModelGroup'):t('modal.addModelGroup')}</h3>{/snippet}
  {#snippet children()}
    <div class="form-group"><label for="modelGroupName">{t('label.modelGroupName')}</label><input id="modelGroupName" bind:value={name} placeholder={t('placeholder.modelGroupName')} /></div>
    <div class="form-group"><label for="modelGroupProvider">{t('label.provider')}</label><select id="modelGroupProvider" value={provider} onchange={(event)=>changeProvider(event.currentTarget.value)}>{#each Object.keys(config.providers??{}) as item}<option value={item}>{item}</option>{/each}</select></div>
    <div class="form-group"><label for="modelGroupToolProfile">{t('tools.profile')}</label><select id="modelGroupToolProfile" bind:value={toolProfile} disabled={!passthroughOption&&!compatibleToolProfiles.length}><option value="">{t('model.providerDefault')}</option>{#if passthroughOption}<option value={passthroughOption.id}>{t('tools.passThrough')}</option>{/if}{#each compatibleToolProfiles as profile}<option value={profile.id}>{profile.name}</option>{/each}</select></div>
    <div class="form-group"><div class="form-label">{t('label.modelMappings')}</div><div>{#each rows as row(row.id)}{@const status=infoStatus(row)}<div class="model-group-row"><input aria-label={t('aria.exposedModel')} bind:value={row.name} placeholder={t('placeholder.exposedModel')} /><input aria-label={t('aria.upstreamModel')} bind:value={row.upstream} placeholder={t('placeholder.upstreamModel')} /><div><div class="model-preset-status" class:detected={status.detected} class:modified={status.modified}>{status.text}</div><div class="model-row-controls"><button class="btn btn-sm" onclick={()=>editInfo(row)}>{t('modelInfo.manual')}</button>{#if hasProviderExtraConfig(row)}<button class="btn btn-sm" onclick={()=>editLimits(row)}>{t('modelInfo.providerLimits',{provider:providerDisplayName()})}</button>{/if}<button class="btn btn-sm btn-danger" onclick={()=>removeRow(row.id)}>{t('btn.remove')}</button></div></div></div>{/each}</div><button class="btn btn-sm" onclick={()=>addRow()}>{t('btn.addMapping')}</button></div>
  {/snippet}
  {#snippet actions()}<button class="btn" onclick={()=>{groupOpen=false;closeEditors();}}>{t('btn.cancel')}</button><button class="btn btn-primary" disabled={busy} onclick={()=>void save()}>{t('btn.save')}</button>{/snippet}
  {#snippet sidecar()}
    <div class="modal model-info-modal" class:open={infoRowId!==null&&infoDraft!==null} role="dialog" aria-modal="true" aria-labelledby="model-info-title">
      {#if infoDraft}
        <div class="modal-header"><h3 id="model-info-title">{t('modelInfo.title')}</h3></div>
        <div class="modal-body">
          <div class="model-info-grid">
            <div class="form-group span-2"><label for="modelInfoSlug">{t('modelInfo.slug')}</label><input id="modelInfoSlug" bind:value={infoDraft.slug}/></div>
            <div class="form-group"><label for="modelInfoDisplayName">{t('modelInfo.displayName')}</label><input id="modelInfoDisplayName" bind:value={infoDraft.display_name}/></div>
            <div class="form-group"><label for="modelInfoIdentity">{t('modelInfo.identity')}</label><input id="modelInfoIdentity" bind:value={infoDraft.identity}/></div>
            <div class="form-group span-2"><label for="modelInfoDescription">{t('modelInfo.description')}</label><textarea id="modelInfoDescription" bind:value={infoDraft.description}></textarea></div>
            <div class="form-group"><label for="modelInfoPriority">{t('modelInfo.priority')}</label><input id="modelInfoPriority" type="number" min="1" bind:value={infoDraft.priority}/></div>
            <div class="form-group"><label for="modelInfoContextWindow">{t('modelInfo.contextWindow')}</label><input id="modelInfoContextWindow" type="number" min="1" bind:value={infoDraft.context_window}/></div>
            <div class="form-group span-2"><div class="form-label">{t('modelInfo.modalities')}</div><div class="checkbox-group model-info-checkbox-group">{#each ['text','image'] as value}<label><input type="checkbox" checked={infoDraft.input_modalities.includes(value)} onchange={(event)=>toggleList('input_modalities',value,event.currentTarget.checked)}/>{t(`modelInfo.modality.${value}`)}</label>{/each}</div></div>
            <div class="form-group span-2"><div class="form-label">{t('modelInfo.reasoningLevels')}</div><div class="checkbox-group model-info-checkbox-group">{#each ['minimal','low','medium','high','xhigh','max','ultra'] as value}<label><input type="checkbox" checked={reasoningValues(infoDraft).includes(value)} onchange={(event)=>toggleList('supported_reasoning_levels',value,event.currentTarget.checked)}/>{t(`modelInfo.reasoning.${value}`)}</label>{/each}</div></div>
          </div>
        </div>
        <div class="modal-actions"><button class="btn" type="button" onclick={clearInfo}>{#if infoRow()&&presetFor(infoRow()!)}{t('modelInfo.restorePreset',{display_name:presetFor(infoRow()!)!.display_name})}{:else}{t('modelInfo.useAutomatic')}{/if}</button><button class="btn" type="button" onclick={closeInfo}>{t('btn.cancel')}</button><button class="btn btn-primary" type="button" onclick={applyInfo}>{t('btn.applyChanges')}</button></div>
      {/if}
    </div>
    <div class="modal model-info-modal" class:open={limitRowId!==null&&runtimeFields().length>0} role="dialog" aria-modal="true" aria-labelledby="provider-limits-title">
      {#if limitRowId!==null}
        <div class="modal-header"><h3 id="provider-limits-title">{t('modelInfo.providerLimitsTitle',{provider:providerDisplayName()})}</h3></div>
        <div class="modal-body">
          <p class="field-hint provider-limit-hint">{t('modelInfo.providerLimitsHint')}</p>
          {#each runtimeFields() as field}
            <div class="provider-limit-row">
              <label class="provider-limit-toggle"><input type="checkbox" checked={Object.hasOwn(runtimeDraft,field)} onchange={(event)=>toggleRuntime(field,event.currentTarget.checked)}/><span>{field}</span></label>
              <input aria-label={field} type="number" min="0" max={field==='temperature'?2:1} step="0.01" disabled={!Object.hasOwn(runtimeDraft,field)} value={runtimeDraft[field]??''} oninput={(event)=>setRuntime(field,event.currentTarget.value===''?null:event.currentTarget.valueAsNumber)}/>
            </div>
          {/each}
        </div>
        <div class="modal-actions"><button class="btn" type="button" onclick={clearLimits}>{t('modelInfo.clearProviderLimits')}</button><button class="btn" type="button" onclick={closeLimits}>{t('btn.cancel')}</button><button class="btn btn-primary" type="button" onclick={applyLimits}>{t('btn.applyChanges')}</button></div>
      {/if}
    </div>
  {/snippet}
</Modal>
<Modal open={fetchOpen} labelledby="fetch-models-title" wide onclose={()=>fetchOpen=false}>{#snippet header()}<h3 id="fetch-models-title">{t('modal.fetchModels')}</h3>{/snippet}<div class="form-group"><label for="fetchProvider">{t('label.selectProvider')}</label><select id="fetchProvider" bind:value={provider}>{#each Object.keys(config.providers??{}) as item}<option value={item}>{item}</option>{/each}</select></div><div class="form-group"><label for="fetchGroupName">{t('label.modelGroupName')}</label><input id="fetchGroupName" bind:value={name} placeholder={t('placeholder.fetchGroupName')} /></div>{#if discovered.length}<div class="fetch-toolbar"><input bind:value={discoveryFilter} placeholder={t('placeholder.filterModels')}/><button class="btn btn-sm" onclick={()=>selectedDiscovered=new Set(filteredDiscovered)}>{t('btn.selectAll')}</button><button class="btn btn-sm" onclick={()=>selectedDiscovered=new Set()}>{t('btn.deselectAll')}</button><span class="fetch-count">{t('format.selected',{count:selectedDiscovered.size})}</span></div><div class="fetch-models-list">{#each filteredDiscovered as model}<label><input type="checkbox" checked={selectedDiscovered.has(model)} onchange={(event)=>selectModel(model,event.currentTarget.checked)}/>{model}</label>{/each}</div><div class="prefix-group"><label for="fetchPrefix">{t('label.modelPrefix')}</label><input id="fetchPrefix" bind:value={prefix} placeholder={t('placeholder.modelPrefix')}/></div>{/if}{#snippet actions()}<button class="btn" onclick={()=>fetchOpen=false}>{t('btn.cancel')}</button>{#if !discovered.length}<button class="btn btn-primary" disabled={busy||!provider} onclick={()=>void discover()}>{t('btn.fetch')}</button>{:else}<button class="btn btn-primary" disabled={!selectedDiscovered.size||!name.trim()} onclick={addSelected}>{t('btn.applyChanges')}</button>{/if}{/snippet}</Modal>
