<script lang="ts">
  import {onMount} from 'svelte';import {api} from '../lib/api';import {t} from '../lib/i18n.svelte';import {createSerialPoll} from '../lib/polling';
  type Settings={provider?:string;tavily_api_key?:string};type Config={server?:{web_search?:Settings}};type Status={configured?:boolean;service_online?:boolean;browser_ready?:boolean;error?:string};
  let provider=$state('tavily');let tavilyKey=$state('');let status=$state<Status|null>(null);let loading=$state(true);let saving=$state(false);let error=$state('');let notice=$state('');
  const message=(value:unknown)=>value instanceof Error?value.message:String(value);const aborted=(value:unknown)=>value instanceof DOMException&&value.name==='AbortError';
  async function loadConfig(signal:AbortSignal){try{const config=await api.get<Config>('/admin/api/config',signal);provider=config.server?.web_search?.provider??'tavily';tavilyKey=config.server?.web_search?.tavily_api_key??'';error='';}catch(cause){if(!aborted(cause))error=message(cause);}finally{loading=false;}}
  async function loadStatus(signal:AbortSignal){try{status=await api.get<Status>('/admin/api/network-search/status',signal);}catch(cause){if(!aborted(cause))status={configured:true,service_online:false,error:message(cause)};}}
  const poll=createSerialPoll(loadStatus,5000);
  async function save(){saving=true;error='';notice='';try{const web_search:Settings={provider};if(provider==='tavily')web_search.tavily_api_key=tavilyKey.trim();const result=await api.put<{server?:{web_search?:Settings}}>('/admin/api/config/server',{web_search});provider=result.server?.web_search?.provider??provider;tavilyKey=result.server?.web_search?.tavily_api_key??'';notice='Web search settings saved.';await poll.runNow();}catch(cause){error=message(cause);}finally{saving=false;}}
  onMount(()=>{const controller=new AbortController();void loadConfig(controller.signal);poll.start();return()=>{controller.abort();poll.stop();};});
</script>
<div class="section"><div class="section-header"><h2>{t('section.basicSearch','Basic Search')}</h2><button class="btn btn-primary btn-sm" disabled={loading||saving} onclick={()=>void save()}>{t('btn.save','Save')}</button></div>{#if error}<div class="toast error show" role="alert">{error}</div>{/if}{#if notice}<div class="toast show" role="status">{notice}</div>{/if}<div class="provider-card" style="max-width:560px"><div class="form-group"><label for="networkSearchProvider">{t('label.searchProvider','Search Provider')}</label><select id="networkSearchProvider" bind:value={provider}><option value="tavily">Tavily</option><option value="self_hosted_google">Self-hosted (Google)</option><option value="self_hosted_bing">Self-hosted (Bing RSS)</option><option value="self_hosted_bing_browser">Self-hosted (Bing Browser)</option></select></div>{#if provider==='tavily'}<div class="form-group"><label for="networkSearchApiKey">{t('label.searchApiKey','API Key')}</label><input id="networkSearchApiKey" type="password" autocomplete="new-password" bind:value={tavilyKey} placeholder={t('label.searchApiKeyPlaceholder','Enter the Tavily API key')} /></div>{/if}</div></div>
<div class="section"><div class="section-header"><h2>{t('section.advancedSearch','Advanced Search')}</h2></div><div class="provider-card" style="max-width:560px"><div class="form-group"><div class="form-label">{t('label.sidecarService','Sidecar Service')}</div><span class="badge" class:badge-success={status?.service_online} class:badge-error={status&&!status.service_online}>{status===null?t('status.checking','Checking'):status.service_online?'Online':status.configured===false?'Not configured':'Offline'}</span></div><div class="form-group"><div class="form-label">{t('label.sidecarBrowser','Browser')}</div><span class="badge" class:badge-success={status?.browser_ready} class:badge-error={status?.service_online&&!status.browser_ready}>{status===null?t('status.unknown','Unknown'):status.browser_ready?'Ready':status?.service_online?'Not ready':'Unknown'}</span></div>{#if status?.error}<div style="font-size:11px;color:var(--text-dim)">{status.error}</div>{/if}</div></div>
