<script lang="ts">
  import {onMount} from 'svelte';import {api,request} from '../lib/api';import {t} from '../../shared/i18n.svelte';import {createSerialPoll} from '../lib/polling';
  type Settings={provider?:string;responses_provider?:string;tavily_api_key?:string};type Provider={api_type?:string;enabled?:boolean};type Config={providers?:Record<string,Provider>;server?:{web_search?:Settings}};type Status={configured?:boolean;service_online?:boolean;browser_ready?:boolean;error?:string};
  let provider=$state('tavily');let responsesProvider=$state('');let tavilyKey=$state('');let providers=$state<Record<string,Provider>>({});let status=$state<Status|null>(null);let loading=$state(true);let saving=$state(false);let testing=$state(false);let testResult=$state('');let testError=$state('');let error=$state('');let notice=$state('');let responsesProviders=$derived(Object.entries(providers).filter(([,item])=>item.api_type==='responses'&&item.enabled!==false).map(([name])=>name).sort());
  const message=(value:unknown)=>value instanceof Error?value.message:String(value);const aborted=(value:unknown)=>value instanceof DOMException&&value.name==='AbortError';
  async function loadConfig(signal:AbortSignal){try{const config=await api.get<Config>('/admin/api/config',signal);providers=config.providers??{};provider=config.server?.web_search?.provider??'tavily';responsesProvider=config.server?.web_search?.responses_provider??responsesProviders[0]??'';tavilyKey=config.server?.web_search?.tavily_api_key??'';error='';}catch(cause){if(!aborted(cause))error=message(cause);}finally{loading=false;}}
  async function loadStatus(signal:AbortSignal){try{status=await api.get<Status>('/admin/api/network-search/status',signal);}catch(cause){if(!aborted(cause))status={configured:true,service_online:false,error:message(cause)};}}
  const poll=createSerialPoll(loadStatus,5000);
  async function save(){saving=true;error='';notice='';try{const web_search:Settings={provider};if(provider==='tavily')web_search.tavily_api_key=tavilyKey.trim();if(provider==='configured_responses_provider')web_search.responses_provider=responsesProvider;const result=await api.put<{server?:{web_search?:Settings}}>('/admin/api/config/server',{web_search});provider=result.server?.web_search?.provider??provider;responsesProvider=result.server?.web_search?.responses_provider??responsesProvider;tavilyKey=result.server?.web_search?.tavily_api_key??'';notice=t('toast.networkSearchSaved');await poll.runNow();}catch(cause){error=message(cause);}finally{saving=false;}}
  async function testSearch(){testing=true;testError='';testResult='';try{const result=await request<unknown>('/admin/api/network-search/test',{method:'POST',responseEffects:'local'});testResult=JSON.stringify(result,null,2)??String(result);}catch(cause){testError=message(cause);}finally{testing=false;}}
  onMount(()=>{const controller=new AbortController();void loadConfig(controller.signal);poll.start();return()=>{controller.abort();poll.stop();};});
</script>
<div class="section"><div class="section-header"><h2>{t('section.basicSearch')}</h2><button class="btn btn-primary btn-sm" disabled={loading||saving||(provider==='configured_responses_provider'&&!responsesProvider)} onclick={()=>void save()}>{t('btn.save')}</button></div>{#if error}<div class="toast error show" role="alert">{error}</div>{/if}{#if notice}<div class="toast show" role="status">{notice}</div>{/if}<div class="provider-card" style="max-width:560px"><div class="form-group"><label for="networkSearchProvider">{t('label.searchProvider')}</label><select id="networkSearchProvider" bind:value={provider}><option value="tavily">{t('network.provider.tavily')}</option><option value="self_hosted_google">{t('network.provider.google')}</option><option value="self_hosted_bing">{t('network.provider.bingRss')}</option><option value="self_hosted_bing_browser">{t('network.provider.bingBrowser')}</option><option value="configured_responses_provider">{t('network.provider.configuredResponses')}</option></select></div>{#if provider==='tavily'}<div class="form-group"><label for="networkSearchApiKey">{t('label.searchApiKey')}</label><input id="networkSearchApiKey" type="password" autocomplete="new-password" bind:value={tavilyKey} placeholder={t('label.searchApiKeyPlaceholder')} /></div>{:else if provider==='configured_responses_provider'}<div class="form-group"><label for="networkSearchResponsesProvider">{t('label.responsesSearchProvider')}</label><select id="networkSearchResponsesProvider" bind:value={responsesProvider} disabled={!responsesProviders.length}>{#if !responsesProviders.length}<option value="">{t('network.provider.noResponses')}</option>{:else}{#each responsesProviders as name}<option value={name}>{name}</option>{/each}{/if}</select></div>{/if}</div></div>
<div class="section"><div class="section-header"><h2>{t('section.searchTest')}</h2></div><div class="provider-card search-test-card" style="max-width:560px"><div class="search-test-query">{t('label.searchTestQuery')}</div><button class="btn btn-primary btn-sm" disabled={testing} onclick={()=>void testSearch()}>{testing?t('status.testing'):t('btn.test')}</button><div class="search-test-response" aria-live="polite"><div class="form-label">{t('label.searchTestResponse')}</div>{#if testError}<pre class="test-output search-test-error" role="alert">{testError}</pre>{:else if testResult}<pre class="test-output">{testResult}</pre>{:else}<div class="search-test-placeholder">{t('label.searchTestEmpty')}</div>{/if}</div></div></div>
<div class="section"><div class="section-header"><h2>{t('section.advancedSearch')}</h2></div><div class="provider-card" style="max-width:560px"><div class="form-group"><div class="form-label">{t('label.sidecarService')}</div><span class="badge" class:badge-success={status?.service_online} class:badge-error={status&&!status.service_online}>{status===null?t('status.checking'):status.service_online?t('status.online'):status.configured===false?t('status.notConfigured'):t('status.offline')}</span></div><div class="form-group"><div class="form-label">{t('label.sidecarBrowser')}</div><span class="badge" class:badge-success={status?.browser_ready} class:badge-error={status?.service_online&&!status.browser_ready}>{status===null?t('status.unknown'):status.browser_ready?t('status.ready'):status?.service_online?t('status.notReady'):t('status.unknown')}</span></div>{#if status?.error}<div style="font-size:11px;color:var(--text-dim)">{status.error}</div>{/if}</div></div>
<style>
  .search-test-card{display:grid;gap:12px;justify-items:start}.search-test-query{font-family:var(--mono);font-size:13px}.search-test-response{width:100%}.search-test-placeholder{padding:12px;border:1px dashed var(--border);border-radius:var(--radius);color:var(--text-dim);font-size:12px}.search-test-error{border-color:var(--red);color:var(--red)}
</style>
